# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jillian Maroket
title: Senior Technical Writer
# email: 
# website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  jillian-maroket
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: cjmaroket
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  With over 10 years of experience in technical communication, I can create user-centered content for help systems, interfaces, and marketing collateral. I have always advocated for clear, consistent writing that facilitates understanding of complex concepts, task completion, and audience engagement. My body of work includes documentation, UX copy, marketing copy, style guides, terminology lists, and process documents.


content:
  - title: What I Do # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Content strategy
        description: Designing conversations between products and users I establish content types, structures, and formats, and use technology to efficiently develop, manage, and deliver content.
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #  I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left 
        title: Documentation writing
        description: Building help systems that enable users to complete tasks I specialize in structured authoring, which is a standardized, methodological approach to content creation.
      - layout: left 
        title: UX writing
        description: Creating user-centered content for web and mobile applications I write interface text (also known as “microcopy”) that addresses what users feel and need at each step of their user journey.
      - layout: left
        title: Technical marketing
        description: Creating content that creates awareness about the specifications and technical aspects of a product or service I write marketing collateral that explain how a product or service works, and how these features will benefit the user.
  
  - title: My Skills # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Information architecture
      - UX writing
      - Documentation writing (for end users and developers)
      - Topic-based authoring using the Darwin Information Typing Architecture (DITA)
      - Marketing writing (articles, datasheets, website copy, video scripts)
      - Structural, technical, and copy editing
      - Audio-visual media production
      - Creation of terminology and style standards
      - Configuration of authoring and publishing environments
      - Project management

  - title: Tools I Use # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Docs-as-code: GitHub, Visual Studio Code
      - XML authoring: Syncro Soft Oxygen, Adobe FrameMaker
      - Content management: SDL Tridion Docs, Umbraco, WordPress
      - Interface design: Figma, Adobe XD
      - Print and web publishing: Adobe InDesign
      - Digital imaging: Adobe Photoshop, TechSmith Snagit
      - Collaboration and productivity: Atlassian Confluence, Notion, Slack

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
