# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jillian Maroket
title: Senior Technical Writer
# email: 
# website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  jillian-maroket
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: cjmaroket
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  With over 15 years of experience in technical communication, I possess a proven track record of distilling technical information into accessible content, enhancing the overall user experience and driving positive outcomes for the organizations I collaborate with. Throughout my career, I have been a staunch advocate for clear and consistent writing, ensuring that users can easily grasp complex concepts, navigate products with confidence, and accomplish tasks seamlessly.

content:
  - title: What I Do # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Documentation Writing
        quote: Building help systems that enable users to understand concepts and complete tasks
        description: I specialize in structured authoring, which is a standardized, methodological approach to content creation.

        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #  I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: left 
        title: UX Writing
        quote: Creating user-centered content for web and mobile applications
        description: I write interface text (also known as "UX copy") that addresses what users feel and need at each step of their user journey.
      - layout: left 
        title: Content Strategy
        quote: Designing conversations between products and users
        description: I establish content types, structures, and formats, and use technology to efficiently develop, manage, and deliver content.

  - title: Sample Work # Title for the section
    layout: list
    content:
    - layout: left
      border: weak
      title: UX Copy | Trend Micro
      description: The service provides a detailed view of threats found across segments of an organization. I wrote the UX copy in early versions of the product console and associated applications.
      link: https://resources.trendmicro.com/security-assessment-service-us.html
      link_text: Trend Micro Security Assessment Service
    - layout: left
      border: weak
      title: UX Copy | Atgenomix
      description: SeqsLab is a cloud-native biomedical information technology platform. I wrote most of the UX copy in the Azure enterprise application.
      link: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/atgenomix.seqslab-v3-azapp
      link_text: SeqsLab V3
    - layout: left
      border: weak
      title: Tutorial | Trend Micro 
      description: These videos show how Trend Micro products can help detect, investigate, and respond to cyberattacks. I wrote the scripts and worked with the multimedia designer in creating the storyboards.
      link:  
      link_text:
      additional_links:
          - title: Trend Micro Worry-Free XDR
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=4QEUy3pzZOU
          - title: Trend Micro Apex One
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=DLiZcT7HzjU


  - title: My Skills # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Information architecture  
      - Structured authoring using the Darwin Information Typing Architecture (DITA)  
      - API documentation  
      - Content delivery using Docs-as-Code workflows  
      - UX writing  
      - Audio-visual media production  
      - Structural, technical, and copy editing  
      - Content strategy  
      - Creation of terminology and style standards  
      - Configuration of authoring and publishing environments 
      - Project management


  - title: Tools and Technology # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Languages: HTML, Markdown, XML, YAML, SQL  
      - XML authoring: Syncro Soft Oxygen, Adobe FrameMaker  
      - Content management: SDL Tridion Docs, Umbraco  
      - Source code editing: Visual Studio Code, Sublime Text  
      - Source code management: GitHub  
      - Interface design: Figma, Adobe XD  
      - Print and web publishing: Adobe InDesign  
      - Digital imaging: Adobe Photoshop, TechSmith Snagit  
      - Collaboration and productivity: Atlassian Confluence and Jira, Notion, Slack

# Footer
# footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
